let _browserLanguage    = window.navigator.userLanguage || window.navigator.language;
const browserLanguage   = String(_browserLanguage.split("-")[0]).toLowerCase();

export let LANGUAGE = {};

const LANGUAGE_NL = [
  'Albanees',
  'Armeens',
  'Azerbeidzjaans',
  'Baskisch',
  'Bosnisch',
  'Bulgaars',
  'Catalaans',
  'Deens',
  'Duits',
  'Engels',
  'Estisch',
  'Faeröers',
  'Fins',
  'Frans',
  'Fries',
  'Galicisch',
  'Georgisch',
  'Grieks',
  'Hongaars',
  'Iers',
  'IJslands',
  'Italiaans',
  'Kroatisch',
  'Macedonisch',
  'Montenegrijns',
  'Nederlands',
  'Noors',
  'Oekraïens',
  'Pools',
  'Portugees',
  'Roemeens',
  'Russisch',
  'Schots',
  'Servisch',
  'Sloveens',
  'Slowaaks',
  'Spaans',
  'Tsjechisch',
  'Turks',
  'Waals',
  'Welsh',
  'Wit-Russisch',
  'Zweeds',
  'Smurfs'
];

const LANGUAGE_EN = [
  'Albanian',
  'Armenian',
  'Azerbaijani',
  'Basque',
  'Bosnian',
  'Bulgarian',
  'Catalan',
  'Danish',
  'German',
  'English',
  'Estonian',
  'Faroese',
  'Finnish',
  'French',
  'Frisian',
  'Galician',
  'Georgian',
  'Greek',
  'Hungarian',
  'Irish',
  'Icelandic',
  'Italian',
  'Croatian',
  'Macedonian',
  'Montenegrin',
  'Dutch',
  'Norwegian',
  'Ukrainian',
  'Polish',
  'Portuguese',
  'Romanian',
  'Russian',
  'Scottish',
  'Serbian',
  'Slovenian',
  'Slovak',
  'Spanish',
  'Czech',
  'Turkish',
  'Walloon',
  'Welsh',
  'Belarusian',
  'Swedish',
  'Smurfs'
];

if(browserLanguage == 'en')
  LANGUAGE = [...LANGUAGE_EN];
else
  LANGUAGE = [...LANGUAGE_NL];